apiVersion: v1
kind: Pod
metadata:
  name: STRING
  namespace: STRING
spec:
  containers:
    - name: STRING
      image: STRING
      imagePullPolicy: STRING  # Always, IfNotPresent, Never
      command: ["STRING"]
      args:
        - STRING
      ports:
        - containerPort: 1234
