apiVersion: v1
kind: Service
metadata:
  name: STRING
  namespace: STRING
spec:
  type: STRING          # ClusterIP (default), NodePort, LoadBalancer, ExternalName
  selector:
    STRING: STRING
  ports:
    - name: STRING      # Optional if only a single port
      port: 1234        # Port exposed by service
      protocol: STRING  # TCP (default), UDP, SCTP
      targetPort: 1234
  externalName: STRING  # Only when spec.type is ExternalName
